contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #assemblyexample channel"
    url: https://nfcore.slack.com/channels/assemblyexample
    about: Discussion about the nf-core/assemblyexample pipeline
